[phases.setup]
nixPkgs = ["python39", "postgresql_16.dev", "gcc"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "gunicorn --chdir backend app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1"